wandb_version: 1

ENV_HPT_mode:
  value: false
ENV_LEARNING_RATE:
  value: 0.003
architecture:
  value: LSTM
features:
  value: EFs
offline_train_test_datasets:
  value: trans_tagging
online_simulation_factor:
  value: 0
seed:
  value: 2
