wandb_version: 1

ENV_HPT_mode:
  value: false
ENV_LEARNING_RATE:
  value: 0.001
architecture:
  value: LSTM
features:
  value: EFs
offline_train_test_datasets:
  value: original_data
seed:
  value: 0
