wandb_version: 1

ENV_HPT_mode:
  value: false
ENV_LEARNING_RATE:
  value: 0.003
architecture:
  value: CNN
features:
  value: EFs
offline_train_test_datasets:
  value: trans_tagging
seed:
  value: 4
